version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../Backend/app:/app/app
      - ../uploads:/app/uploads
      - ../chroma_db:/app/chroma_db
    environment:
      - ENVIRONMENT=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:

networks:
  langchain-net:
    driver: bridge 