/*
Deployment script for NewDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "NewDB"
:setvar DefaultFilePrefix "NewDB"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Account]...';


GO
CREATE TABLE [dbo].[Account] (
    [AccountId]            VARCHAR (50)  NOT NULL,
    [FirmId]               VARCHAR (10)  NOT NULL,
    [AlgoSuiteId]          VARCHAR (50)  NULL,
    [TradeSummaryTemplate] VARCHAR (50)  NULL,
    [TradeAdviceTemplate]  VARCHAR (50)  NULL,
    [BookId]               VARCHAR (50)  NULL,
    [DynamicAttributes]    VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Account_1] PRIMARY KEY CLUSTERED ([AccountId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AccountDestination]...';


GO
CREATE TABLE [dbo].[AccountDestination] (
    [AccountId]         VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DestinationId]     VARCHAR (10)  NOT NULL,
    [DestinationCode]   INT           NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AccountDestination] PRIMARY KEY CLUSTERED ([AccountId] ASC, [FirmId] ASC, [DestinationId] ASC, [DestinationCode] ASC)
);


GO
PRINT N'Creating Table [dbo].[AccountGroup]...';


GO
CREATE TABLE [dbo].[AccountGroup] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AccountGroup] PRIMARY KEY CLUSTERED ([GroupId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AccountGroupMember]...';


GO
CREATE TABLE [dbo].[AccountGroupMember] (
    [GroupAssociationId] UNIQUEIDENTIFIER NOT NULL,
    [GroupId]            VARCHAR (50)     NOT NULL,
    [FirmId]             VARCHAR (10)     NOT NULL,
    [MemberGroupId]      VARCHAR (50)     NULL,
    [AccountId]          VARCHAR (50)     NULL,
    [DynamicAttributes]  VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AccountGroupMember] PRIMARY KEY CLUSTERED ([GroupAssociationId] ASC),
    CONSTRAINT [IX_AccountGroupMember] UNIQUE NONCLUSTERED ([FirmId] ASC, [GroupId] ASC, [MemberGroupId] ASC, [AccountId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AccountIOIDestination]...';


GO
CREATE TABLE [dbo].[AccountIOIDestination] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [AccountId]         VARCHAR (50)  NOT NULL,
    [DestinationId]     VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AccountIOIDestination] PRIMARY KEY CLUSTERED ([FirmId] ASC, [AccountId] ASC, [DestinationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ACTSettings]...';


GO
CREATE TABLE [dbo].[ACTSettings] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [RefId]             VARCHAR (50)  NOT NULL,
    [SettingType]       INT           NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ACTSettings] PRIMARY KEY CLUSTERED ([FirmId] ASC, [RefId] ASC, [SettingType] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoStrategy]...';


GO
CREATE TABLE [dbo].[AlgoStrategy] (
    [AlgoStrategyId]      UNIQUEIDENTIFIER NOT NULL,
    [FirmId]              VARCHAR (10)     NOT NULL,
    [AlgoSuiteId]         VARCHAR (50)     NOT NULL,
    [InAlgoSuiteId]       VARCHAR (50)     NOT NULL,
    [InStrategyId]        VARCHAR (50)     NOT NULL,
    [AssetType]           INT              NOT NULL,
    [DestinationId]       VARCHAR (10)     NOT NULL,
    [DestinationCode]     INT              NOT NULL,
    [DestinationStrategy] VARCHAR (50)     NULL,
    [DynamicAttributes]   VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AlgoStrategy] PRIMARY KEY CLUSTERED ([AlgoStrategyId] ASC),
    CONSTRAINT [IX_AlgoStrategy_1] UNIQUE NONCLUSTERED ([FirmId] ASC, [AlgoSuiteId] ASC, [InAlgoSuiteId] ASC, [InStrategyId] ASC, [AssetType] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoSuite]...';


GO
CREATE TABLE [dbo].[AlgoSuite] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [AlgoSuiteId]       VARCHAR (50)  NOT NULL,
    [InAlgoSuiteId]     VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AlgoTemplate] PRIMARY KEY CLUSTERED ([FirmId] ASC, [AlgoSuiteId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoTagMap]...';


GO
CREATE TABLE [dbo].[AlgoTagMap] (
    [AlgoTagMapId]           UNIQUEIDENTIFIER NOT NULL,
    [AlgoStrategyId]         UNIQUEIDENTIFIER NOT NULL,
    [InAlgoStrategyTagMapId] UNIQUEIDENTIFIER NULL,
    [DestinationTag]         VARCHAR (50)     NOT NULL,
    [DynamicAttributes]      VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AlgoStrategyTagMap] PRIMARY KEY CLUSTERED ([AlgoTagMapId] ASC),
    CONSTRAINT [IX_AlgoStrategyTagMap] UNIQUE NONCLUSTERED ([AlgoStrategyId] ASC, [DestinationTag] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoWheelStrategy]...';


GO
CREATE TABLE [dbo].[AlgoWheelStrategy] (
    [AlgoWheelStrategyId] UNIQUEIDENTIFIER NOT NULL,
    [FirmId]              VARCHAR (10)     NOT NULL,
    [AlgoWheelSuiteId]    VARCHAR (50)     NOT NULL,
    [DestinationId]       VARCHAR (10)     NOT NULL,
    [DestinationCode]     INT              NOT NULL,
    [DestinationStrategy] VARCHAR (50)     NULL,
    [DynamicAttributes]   VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AlgoWheelStrategy] PRIMARY KEY CLUSTERED ([AlgoWheelStrategyId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoWheelSuite]...';


GO
CREATE TABLE [dbo].[AlgoWheelSuite] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [AlgoWheelSuiteId]  VARCHAR (50)  NOT NULL,
    [InAlgoSuiteId]     VARCHAR (50)  NOT NULL,
    [InStrategyId]      VARCHAR (50)  NOT NULL,
    [AssetType]         INT           NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AlgoWheelSuite] PRIMARY KEY CLUSTERED ([FirmId] ASC, [AlgoWheelSuiteId] ASC),
    CONSTRAINT [IX_AlgoWheelSuite] UNIQUE NONCLUSTERED ([FirmId] ASC, [AlgoWheelSuiteId] ASC, [InAlgoSuiteId] ASC, [InStrategyId] ASC, [AssetType] ASC)
);


GO
PRINT N'Creating Table [dbo].[AlgoWheelTagMap]...';


GO
CREATE TABLE [dbo].[AlgoWheelTagMap] (
    [AlgoWheelTagMapId]      UNIQUEIDENTIFIER NOT NULL,
    [AlgoWheelStrategyId]    UNIQUEIDENTIFIER NOT NULL,
    [InAlgoStrategyTagMapId] UNIQUEIDENTIFIER NULL,
    [DestinationTag]         VARCHAR (50)     NOT NULL,
    [DynamicAttributes]      VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AlgoWheelStrategyTagMap] PRIMARY KEY CLUSTERED ([AlgoWheelTagMapId] ASC),
    CONSTRAINT [IX_AlgoWheelStrategyTagMap] UNIQUE NONCLUSTERED ([AlgoWheelStrategyId] ASC, [DestinationTag] ASC)
);


GO
PRINT N'Creating Table [dbo].[App]...';


GO
CREATE TABLE [dbo].[App] (
    [AppId]             VARCHAR (20)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_App] PRIMARY KEY CLUSTERED ([AppId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppInstance]...';


GO
CREATE TABLE [dbo].[AppInstance] (
    [AppInstanceId]     VARCHAR (20)  NOT NULL,
    [AppId]             VARCHAR (20)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AppServer] PRIMARY KEY CLUSTERED ([AppInstanceId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppUpdate]...';


GO
CREATE TABLE [dbo].[AppUpdate] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [UserId]            VARCHAR (50)  NOT NULL,
    [ProductId]         VARCHAR (20)  NOT NULL,
    [Version]           VARCHAR (20)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AppUpdate_1] PRIMARY KEY CLUSTERED ([FirmId] ASC, [UserId] ASC, [ProductId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppUser]...';


GO
CREATE TABLE [dbo].[AppUser] (
    [UserId]                 VARCHAR (50)  NOT NULL,
    [PasswordUpdateDateTime] DATETIME      NULL,
    [PasswordResetFlag]      INT           NULL,
    [DynamicAttributes]      VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AppUser] PRIMARY KEY CLUSTERED ([UserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppUserFixSubscription]...';


GO
CREATE TABLE [dbo].[AppUserFixSubscription] (
    [SubscriptionId]    VARCHAR (50)  NOT NULL,
    [UserId]            VARCHAR (50)  NOT NULL,
    [SubscriptionType]  INT           NOT NULL,
    [FixSessionId]      VARCHAR (50)  NULL,
    [FixSessionGroupId] VARCHAR (50)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AppUserFixSubscription] PRIMARY KEY CLUSTERED ([SubscriptionId] ASC),
    CONSTRAINT [IX_AppUserFixSubscription] UNIQUE NONCLUSTERED ([FixSessionGroupId] ASC, [FixSessionId] ASC, [UserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppUserSubscription]...';


GO
CREATE TABLE [dbo].[AppUserSubscription] (
    [SubscriptionId]    UNIQUEIDENTIFIER NOT NULL,
    [UserId]            VARCHAR (50)     NOT NULL,
    [SubscriptionType]  INT              NOT NULL,
    [AppType]           INT              NOT NULL,
    [FirmId]            VARCHAR (10)     NULL,
    [FirmGroupId]       VARCHAR (50)     NULL,
    [RoleId]            VARCHAR (50)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_AppUserSubscription] PRIMARY KEY CLUSTERED ([SubscriptionId] ASC),
    CONSTRAINT [IX_AppUserSubscription] UNIQUE NONCLUSTERED ([AppType] ASC, [FirmGroupId] ASC, [FirmId] ASC, [SubscriptionType] ASC, [UserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AppVersion]...';


GO
CREATE TABLE [dbo].[AppVersion] (
    [ProductId]         VARCHAR (20)  NOT NULL,
    [Version]           VARCHAR (20)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AppVersion] PRIMARY KEY CLUSTERED ([ProductId] ASC, [Version] ASC)
);


GO
PRINT N'Creating Table [dbo].[Book]...';


GO
CREATE TABLE [dbo].[Book] (
    [BookId]            VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [ParentBookId]      VARCHAR (50)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED ([FirmId] ASC, [BookId] ASC)
);


GO
PRINT N'Creating Table [dbo].[BookGroup]...';


GO
CREATE TABLE [dbo].[BookGroup] (
    [BookGroupId]       VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_BookGroup] PRIMARY KEY CLUSTERED ([BookGroupId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[BookGroupMember]...';


GO
CREATE TABLE [dbo].[BookGroupMember] (
    [BookGroupMemberId] UNIQUEIDENTIFIER NOT NULL,
    [BookGroupId]       VARCHAR (50)     NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [BookGroupInBGroup] VARCHAR (50)     NULL,
    [BookId]            VARCHAR (50)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_BookGroupMember] PRIMARY KEY CLUSTERED ([BookGroupMemberId] ASC)
);


GO
PRINT N'Creating Table [dbo].[BookMember]...';


GO
CREATE TABLE [dbo].[BookMember] (
    [MemberId]          UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [ParentBookId]      VARCHAR (50)     NOT NULL,
    [ChildBookId]       VARCHAR (50)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_BookMember] PRIMARY KEY CLUSTERED ([MemberId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ChatGroup]...';


GO
CREATE TABLE [dbo].[ChatGroup] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ChatGroup] PRIMARY KEY CLUSTERED ([GroupId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ChatGroupMember]...';


GO
CREATE TABLE [dbo].[ChatGroupMember] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [UserId]            VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ChatGroupMember] PRIMARY KEY CLUSTERED ([GroupId] ASC, [FirmId] ASC, [UserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[CommRule]...';


GO
CREATE TABLE [dbo].[CommRule] (
    [RuleId]            UNIQUEIDENTIFIER NOT NULL,
    [RulesetId]         VARCHAR (50)     NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [ScheduleId]        VARCHAR (50)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_CommRule] PRIMARY KEY CLUSTERED ([RuleId] ASC)
);


GO
PRINT N'Creating Table [dbo].[CommRuleset]...';


GO
CREATE TABLE [dbo].[CommRuleset] (
    [RulesetId]         VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CommRuleset] PRIMARY KEY CLUSTERED ([RulesetId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[CommRulesetAccount]...';


GO
CREATE TABLE [dbo].[CommRulesetAccount] (
    [RulesetAccountId] UNIQUEIDENTIFIER NOT NULL,
    [FirmId]           VARCHAR (10)     NOT NULL,
    [AccountId]        VARCHAR (50)     NOT NULL,
    [SubAccountId]     VARCHAR (50)     NULL,
    [RulesetId]        VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_CommRulesetAccount] PRIMARY KEY CLUSTERED ([RulesetAccountId] ASC)
);


GO
PRINT N'Creating Table [dbo].[CommSchedule]...';


GO
CREATE TABLE [dbo].[CommSchedule] (
    [ScheduleId]        VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CommSchedule] PRIMARY KEY CLUSTERED ([ScheduleId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Country]...';


GO
CREATE TABLE [dbo].[Country] (
    [Code]              VARCHAR (20)  NOT NULL,
    [ISOCode]           VARCHAR (2)   NULL,
    [MIC]               VARCHAR (4)   NULL,
    [BillingCode]       VARCHAR (20)  NULL,
    [RegSettleCycle]    INT           NULL,
    [PQCode]            VARCHAR (20)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Code] ASC)
);


GO
PRINT N'Creating Table [dbo].[CustomerRoutingRule]...';


GO
CREATE TABLE [dbo].[CustomerRoutingRule] (
    [RuleId]                VARCHAR (50)  NOT NULL,
    [FirmId]                VARCHAR (10)  NOT NULL,
    [DestinationId]         VARCHAR (10)  NULL,
    [DestinationCode]       INT           NULL,
    [BackupDestinationId]   VARCHAR (10)  NULL,
    [BackupDestinationCode] INT           NULL,
    [FracDestinationId]     VARCHAR (10)  NULL,
    [FracDestinationCode]   INT           NULL,
    [AlgoSuiteId]           VARCHAR (50)  NULL,
    [WheelId]               VARCHAR (50)  NULL,
    [AlgoWheelSuiteId]      VARCHAR (50)  NULL,
    [DynamicAttributes]     VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CustomerRoutingRule] PRIMARY KEY CLUSTERED ([RuleId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Destination]...';


GO
CREATE TABLE [dbo].[Destination] (
    [DestinationId]     VARCHAR (10)  NOT NULL,
    [CustomerId]        INT           NULL,
    [ExchangeCode]      VARCHAR (50)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK__Destination] PRIMARY KEY CLUSTERED ([DestinationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[EmailTag]...';


GO
CREATE TABLE [dbo].[EmailTag] (
    [TagName]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_EmailTag] PRIMARY KEY CLUSTERED ([TagName] ASC)
);


GO
PRINT N'Creating Table [dbo].[EmailTemplate]...';


GO
CREATE TABLE [dbo].[EmailTemplate] (
    [TemplateId]        UNIQUEIDENTIFIER NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_EmailTemplate] PRIMARY KEY CLUSTERED ([TemplateId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ETBFirmList]...';


GO
CREATE TABLE [dbo].[ETBFirmList] (
    [ETBListId]         VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ETBFirmList] PRIMARY KEY CLUSTERED ([ETBListId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ETBList]...';


GO
CREATE TABLE [dbo].[ETBList] (
    [ETBListId]         VARCHAR (50)  NOT NULL,
    [LocateInfo]        VARCHAR (50)  NULL,
    [ContactName]       VARCHAR (50)  NULL,
    [FileName]          VARCHAR (50)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ETBList] PRIMARY KEY CLUSTERED ([ETBListId] ASC),
    CONSTRAINT [IX_ETBList] UNIQUE NONCLUSTERED ([ContactName] ASC, [FileName] ASC, [LocateInfo] ASC)
);


GO
PRINT N'Creating Table [dbo].[Exchange]...';


GO
CREATE TABLE [dbo].[Exchange] (
    [Code]              VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ExchangeConfig] PRIMARY KEY CLUSTERED ([Code] ASC)
);


GO
PRINT N'Creating Table [dbo].[Firm]...';


GO
CREATE TABLE [dbo].[Firm] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [OMSServerId]       VARCHAR (10)  NULL,
    [RMSServerId]       VARCHAR (10)  NULL,
    [AllocServerId]     VARCHAR (10)  NULL,
    [CustomerId]        INT           NULL,
    [ETBListId]         VARCHAR (50)  NULL,
    [RoleId]            VARCHAR (50)  NULL,
    [ParentFirm]        VARCHAR (10)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK__Firm__1F1F209C99D16BF3] PRIMARY KEY CLUSTERED ([FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmDestination]...';


GO
CREATE TABLE [dbo].[FirmDestination] (
    [FirmId]               VARCHAR (10)  NOT NULL,
    [DestinationId]        VARCHAR (10)  NOT NULL,
    [DestinationCode]      INT           NOT NULL,
    [FixSessionId]         VARCHAR (50)  NULL,
    [ProtectedQuoteId]     VARCHAR (50)  NULL,
    [CustomerId]           INT           NULL,
    [RFQFirmDestinationId] VARCHAR (10)  NULL,
    [ExchangeCode]         VARCHAR (20)  NULL,
    [DynamicAttributes]    VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmDestination] PRIMARY KEY CLUSTERED ([FirmId] ASC, [DestinationId] ASC, [DestinationCode] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmGroup]...';


GO
CREATE TABLE [dbo].[FirmGroup] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmGroup] PRIMARY KEY CLUSTERED ([GroupId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmGroupMember]...';


GO
CREATE TABLE [dbo].[FirmGroupMember] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmGroupMember] PRIMARY KEY CLUSTERED ([FirmId] ASC, [GroupId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmRiskSetting]...';


GO
CREATE TABLE [dbo].[FirmRiskSetting] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmRiskSetting] PRIMARY KEY CLUSTERED ([FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmSetting]...';


GO
CREATE TABLE [dbo].[FirmSetting] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmSetting] PRIMARY KEY CLUSTERED ([FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FirmSubscription]...';


GO
CREATE TABLE [dbo].[FirmSubscription] (
    [PrimaryFirmId]     VARCHAR (10)  NOT NULL,
    [SubFirmId]         VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmSubscription] PRIMARY KEY CLUSTERED ([PrimaryFirmId] ASC, [SubFirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FixSession]...';


GO
CREATE TABLE [dbo].[FixSession] (
    [FixSessionId]      VARCHAR (50)  NOT NULL,
    [SessionName]       VARCHAR (50)  NULL,
    [FixEngineId]       VARCHAR (10)  NULL,
    [BkpFixEngineId]    VARCHAR (10)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FixSession_1] PRIMARY KEY CLUSTERED ([FixSessionId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FixSessionGroup]...';


GO
CREATE TABLE [dbo].[FixSessionGroup] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FixSessionGroup] PRIMARY KEY CLUSTERED ([GroupId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FixSessionGroupMember]...';


GO
CREATE TABLE [dbo].[FixSessionGroupMember] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FixSessionId]      VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FixSessionGroupMember] PRIMARY KEY CLUSTERED ([GroupId] ASC, [FixSessionId] ASC)
);


GO
PRINT N'Creating Table [dbo].[FTPServer]...';


GO
CREATE TABLE [dbo].[FTPServer] (
    [ServerId]          UNIQUEIDENTIFIER NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_FTPServer] PRIMARY KEY CLUSTERED ([ServerId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Gateway]...';


GO
CREATE TABLE [dbo].[Gateway] (
    [Name]              VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_GatewayConfig] PRIMARY KEY CLUSTERED ([Name] ASC)
);


GO
PRINT N'Creating Table [dbo].[Holiday]...';


GO
CREATE TABLE [dbo].[Holiday] (
    [Calendar]          VARCHAR (20)  NOT NULL,
    [Date]              DATE          NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Holiday] PRIMARY KEY CLUSTERED ([Calendar] ASC, [Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[InAlgoFirmSubscription]...';


GO
CREATE TABLE [dbo].[InAlgoFirmSubscription] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [InAlgoSuiteId]     VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_InAlgoFirmSubscription] PRIMARY KEY CLUSTERED ([FirmId] ASC, [InAlgoSuiteId] ASC)
);


GO
PRINT N'Creating Table [dbo].[InAlgoStrategy]...';


GO
CREATE TABLE [dbo].[InAlgoStrategy] (
    [InStrategyId]      VARCHAR (50)  NOT NULL,
    [InAlgoSuiteId]     VARCHAR (50)  NOT NULL,
    [StrategyName]      VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_InAlgoStrategy] PRIMARY KEY CLUSTERED ([InStrategyId] ASC, [InAlgoSuiteId] ASC),
    CONSTRAINT [IX_InAlgoStrategy] UNIQUE NONCLUSTERED ([InAlgoSuiteId] ASC, [InStrategyId] ASC),
    CONSTRAINT [IX_InAlgoStrategy_1] UNIQUE NONCLUSTERED ([InAlgoSuiteId] ASC, [StrategyName] ASC)
);


GO
PRINT N'Creating Table [dbo].[InAlgoStrategyTagMap]...';


GO
CREATE TABLE [dbo].[InAlgoStrategyTagMap] (
    [InAlgoStrategyTagMapId] UNIQUEIDENTIFIER NOT NULL,
    [InAlgoSuiteId]          VARCHAR (50)     NOT NULL,
    [InStrategyId]           VARCHAR (50)     NOT NULL,
    [InAlgoTagId]            UNIQUEIDENTIFIER NOT NULL,
    [DynamicAttributes]      VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_InAlgoStrategyTagMap] PRIMARY KEY CLUSTERED ([InAlgoStrategyTagMapId] ASC),
    CONSTRAINT [IX_InAlgoStrategyTagMap] UNIQUE NONCLUSTERED ([InAlgoTagId] ASC, [InStrategyId] ASC, [InAlgoSuiteId] ASC)
);


GO
PRINT N'Creating Table [dbo].[InAlgoSuite]...';


GO
CREATE TABLE [dbo].[InAlgoSuite] (
    [InAlgoSuiteId]     VARCHAR (50)  NOT NULL,
    [StrategyTag]       INT           NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_InAlgoSuite] PRIMARY KEY CLUSTERED ([InAlgoSuiteId] ASC)
);


GO
PRINT N'Creating Table [dbo].[InAlgoTag]...';


GO
CREATE TABLE [dbo].[InAlgoTag] (
    [InAlgoTagId]       UNIQUEIDENTIFIER NOT NULL,
    [InAlgoSuiteId]     VARCHAR (50)     NOT NULL,
    [TagNo]             INT              NOT NULL,
    [TagName]           VARCHAR (50)     NOT NULL,
    [TagType]           INT              NOT NULL,
    [Required]          BIT              NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_InAlgoTag] PRIMARY KEY CLUSTERED ([InAlgoTagId] ASC),
    CONSTRAINT [IX_InAlgoTag] UNIQUE NONCLUSTERED ([InAlgoSuiteId] ASC, [TagNo] ASC, [TagName] ASC)
);


GO
PRINT N'Creating Table [dbo].[IOICustomerGroup]...';


GO
CREATE TABLE [dbo].[IOICustomerGroup] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [GroupId]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_IOICustomerGroup] PRIMARY KEY CLUSTERED ([FirmId] ASC, [GroupId] ASC)
);


GO
PRINT N'Creating Table [dbo].[IOICustomerGroupMember]...';


GO
CREATE TABLE [dbo].[IOICustomerGroupMember] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [GroupId]           VARCHAR (50)  NOT NULL,
    [AccountId]         VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_IOICustomerGroupMember] PRIMARY KEY CLUSTERED ([FirmId] ASC, [GroupId] ASC, [AccountId] ASC)
);


GO
PRINT N'Creating Table [dbo].[IOIFirmDestination]...';


GO
CREATE TABLE [dbo].[IOIFirmDestination] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    [DestinationId]     VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_IOIFirmDestination] PRIMARY KEY CLUSTERED ([FirmId] ASC, [DestinationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[IOISettings]...';


GO
CREATE TABLE [dbo].[IOISettings] (
    [IOISettingId]      UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_IOISettings] PRIMARY KEY CLUSTERED ([IOISettingId] ASC)
);


GO
PRINT N'Creating Table [dbo].[MarketMaker]...';


GO
CREATE TABLE [dbo].[MarketMaker] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [Symbol]            VARCHAR (50)  NOT NULL,
    [LoginId]           VARCHAR (50)  NULL,
    [AccountId]         VARCHAR (50)  NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    [BookId]            VARCHAR (50)  NULL,
    CONSTRAINT [PK_MarketMaker] PRIMARY KEY CLUSTERED ([FirmId] ASC, [Symbol] ASC)
);


GO
PRINT N'Creating Table [dbo].[PriceBand]...';


GO
CREATE TABLE [dbo].[PriceBand] (
    [BandId]            UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [Symbol]            VARCHAR (50)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_Band] PRIMARY KEY CLUSTERED ([BandId] ASC)
);


GO
PRINT N'Creating Table [dbo].[PriceProfile]...';


GO
CREATE TABLE [dbo].[PriceProfile] (
    [PriceProfileId]    UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_PriceProfile] PRIMARY KEY CLUSTERED ([PriceProfileId] ASC),
    CONSTRAINT [IX_PriceProfile] UNIQUE NONCLUSTERED ([PriceProfileId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[PriceProfileBand]...';


GO
CREATE TABLE [dbo].[PriceProfileBand] (
    [PriceBandId]       UNIQUEIDENTIFIER NOT NULL,
    [PriceProfileId]    UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_PriceProfileBand] PRIMARY KEY CLUSTERED ([PriceBandId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ProtectedQuotes]...';


GO
CREATE TABLE [dbo].[ProtectedQuotes] (
    [Code]              VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ProtectedQuotes] PRIMARY KEY CLUSTERED ([Code] ASC)
);


GO
PRINT N'Creating Table [dbo].[Recipient]...';


GO
CREATE TABLE [dbo].[Recipient] (
    [Email]             VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Recipient] PRIMARY KEY CLUSTERED ([Email] ASC)
);


GO
PRINT N'Creating Table [dbo].[Report]...';


GO
CREATE TABLE [dbo].[Report] (
    [ReportId]                VARCHAR (32)  NOT NULL,
    [FirmId]                  VARCHAR (10)  NULL,
    [TemplateId]              VARCHAR (32)  NULL,
    [Billable]                BIT           NULL,
    [Description]             VARCHAR (50)  NULL,
    [IsClearingInterfaceFile] BIT           NULL,
    [ReportType]              INT           NOT NULL,
    [DynamicAttributes]       VARCHAR (MAX) NULL,
    [CustomerId]              INT           NULL,
    CONSTRAINT [PK_ReportJob] PRIMARY KEY CLUSTERED ([ReportId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReportConfig]...';


GO
CREATE TABLE [dbo].[ReportConfig] (
    [ReportTypeNo]            INT           NOT NULL,
    [ReportType]              VARCHAR (50)  NULL,
    [FileType]                INT           NOT NULL,
    [EntityType]              INT           NULL,
    [Description]             VARCHAR (250) NULL,
    [IsClearingInterfaceFile] BIT           NULL,
    [DynamicAttributes]       VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ReportConfig] PRIMARY KEY CLUSTERED ([ReportTypeNo] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReportDetail]...';


GO
CREATE TABLE [dbo].[ReportDetail] (
    [ReportDetailId]    UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [ReportId]          VARCHAR (32)     NOT NULL,
    [TemplateId]        VARCHAR (32)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_ReportDetail_1] PRIMARY KEY CLUSTERED ([ReportDetailId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReportTemplate]...';


GO
CREATE TABLE [dbo].[ReportTemplate] (
    [TemplateId]        VARCHAR (32)  NOT NULL,
    [Billable]          BIT           NULL,
    [ReportType]        INT           NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ReportTemplate] PRIMARY KEY CLUSTERED ([TemplateId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RFQFirmDestination]...';


GO
CREATE TABLE [dbo].[RFQFirmDestination] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DestinationId]     VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_RFQFirmDestination] PRIMARY KEY CLUSTERED ([FirmId] ASC, [DestinationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RiskLimit]...';


GO
CREATE TABLE [dbo].[RiskLimit] (
    [RiskLimitId]       INT              NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [TraderId]          VARCHAR (50)     NULL,
    [AccountId]         VARCHAR (50)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    [PriceProfileId]    UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_RiskLimit] PRIMARY KEY CLUSTERED ([RiskLimitId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RiskLimitAuditTrail]...';


GO
CREATE TABLE [dbo].[RiskLimitAuditTrail] (
    [AuditId]         UNIQUEIDENTIFIER NOT NULL,
    [TransactionDate] DATE             NOT NULL,
    [TransactionTime] TIME (7)         NOT NULL,
    [RiskLimitId]     INT              NOT NULL,
    [FirmId]          VARCHAR (10)     NOT NULL,
    [TraderId]        VARCHAR (50)     NULL,
    [Message]         VARBINARY (MAX)  NULL,
    CONSTRAINT [PK_RiskLimitAuditTrail] PRIMARY KEY CLUSTERED ([AuditId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Role]...';


GO
CREATE TABLE [dbo].[Role] (
    [RoleId]            VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_FirmRole] PRIMARY KEY CLUSTERED ([RoleId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RoutingRule]...';


GO
CREATE TABLE [dbo].[RoutingRule] (
    [RoutingRuleId]     UNIQUEIDENTIFIER NOT NULL,
    [Name]              VARCHAR (50)     NULL,
    [FirmId]            VARCHAR (10)     NULL,
    [DestinationId]     VARCHAR (10)     NULL,
    [IOIDestinationId]  VARCHAR (10)     NULL,
    [FixSessionId]      VARCHAR (50)     NULL,
    [DestinationCode]   INT              NULL,
    [RoutingRuleType]   INT              NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_RoutingRule_1] PRIMARY KEY CLUSTERED ([RoutingRuleId] ASC),
    CONSTRAINT [IX_RoutingRule] UNIQUE NONCLUSTERED ([Name] ASC, [RoutingRuleType] ASC, [FirmId] ASC, [FixSessionId] ASC, [DestinationCode] ASC, [DestinationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RSPCustomerRule]...';


GO
CREATE TABLE [dbo].[RSPCustomerRule] (
    [RSPRuleId]         VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_RSPRule] PRIMARY KEY CLUSTERED ([RSPRuleId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[RSPCustomerRuleAccount]...';


GO
CREATE TABLE [dbo].[RSPCustomerRuleAccount] (
    [RSPRuleAccountId] UNIQUEIDENTIFIER NOT NULL,
    [FirmId]           VARCHAR (10)     NOT NULL,
    [AccountId]        VARCHAR (50)     NOT NULL,
    [RSPRuleId]        VARCHAR (50)     NOT NULL,
    CONSTRAINT [PK_RSPRuleAccount] PRIMARY KEY CLUSTERED ([RSPRuleAccountId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ScheduledJob]...';


GO
CREATE TABLE [dbo].[ScheduledJob] (
    [JobId]             UNIQUEIDENTIFIER NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_ScheduledJob] PRIMARY KEY CLUSTERED ([JobId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Schema]...';


GO
CREATE TABLE [dbo].[Schema] (
    [Version] VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_Schema] PRIMARY KEY CLUSTERED ([Version] ASC)
);


GO
PRINT N'Creating Table [dbo].[SSOConfig]...';


GO
CREATE TABLE [dbo].[SSOConfig] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_SSOConfig] PRIMARY KEY CLUSTERED ([FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[StockConfig]...';


GO
CREATE TABLE [dbo].[StockConfig] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [Symbol]            VARCHAR (50)  NOT NULL,
    [LoginId]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_StockConfig] PRIMARY KEY CLUSTERED ([FirmId] ASC, [Symbol] ASC)
);


GO
PRINT N'Creating Table [dbo].[SubAccount]...';


GO
CREATE TABLE [dbo].[SubAccount] (
    [SubAccountId]      VARCHAR (50)  NOT NULL,
    [AccountId]         VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_SubAccount_1] PRIMARY KEY CLUSTERED ([SubAccountId] ASC, [AccountId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Task]...';


GO
CREATE TABLE [dbo].[Task] (
    [TaskId]            UNIQUEIDENTIFIER NOT NULL,
    [JobId]             UNIQUEIDENTIFIER NOT NULL,
    [Step]              INT              NOT NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_Task_1] PRIMARY KEY CLUSTERED ([TaskId] ASC)
);


GO
PRINT N'Creating Table [dbo].[TradeTemplate]...';


GO
CREATE TABLE [dbo].[TradeTemplate] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [TradeTemplateName] VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_TradeTemplate_1] PRIMARY KEY CLUSTERED ([FirmId] ASC, [TradeTemplateName] ASC)
);


GO
PRINT N'Creating Index [dbo].[TradeTemplate].[IX_TradeTemplate]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TradeTemplate]
    ON [dbo].[TradeTemplate]([FirmId] ASC, [TradeTemplateName] ASC);


GO
PRINT N'Creating Table [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [UserId]                 VARCHAR (50)  NOT NULL,
    [FirmId]                 VARCHAR (10)  NULL,
    [PasswordUpdateDateTime] DATETIME      NULL,
    [PasswordResetFlag]      INT           NULL,
    [LoginId]                VARCHAR (50)  NOT NULL,
    [RoleId]                 VARCHAR (50)  NULL,
    [DynamicAttributes]      VARCHAR (MAX) NULL,
    [BookId]                 VARCHAR (50)  NULL,
    CONSTRAINT [PK_User_1] PRIMARY KEY CLUSTERED ([UserId] ASC),
    CONSTRAINT [IX_User] UNIQUE NONCLUSTERED ([FirmId] ASC, [LoginId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserAccounts]...';


GO
CREATE TABLE [dbo].[UserAccounts] (
    [UserAccountGroupId] UNIQUEIDENTIFIER NOT NULL,
    [UserId]             VARCHAR (50)     NOT NULL,
    [AccountId]          VARCHAR (50)     NULL,
    [GroupId]            VARCHAR (50)     NULL,
    [FirmId]             VARCHAR (10)     NOT NULL,
    [DynamicAttributes]  VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_UserAccounts] PRIMARY KEY CLUSTERED ([UserAccountGroupId] ASC),
    CONSTRAINT [IX_UserAccounts] UNIQUE NONCLUSTERED ([FirmId] ASC, [GroupId] ASC, [AccountId] ASC, [UserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserBook]...';


GO
CREATE TABLE [dbo].[UserBook] (
    [UserBookGroupId]   UNIQUEIDENTIFIER NOT NULL,
    [FirmId]            VARCHAR (10)     NOT NULL,
    [UserId]            VARCHAR (50)     NOT NULL,
    [BookId]            VARCHAR (50)     NULL,
    [BookGroupId]       VARCHAR (50)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_UserBook] PRIMARY KEY CLUSTERED ([UserBookGroupId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserGroup]...';


GO
CREATE TABLE [dbo].[UserGroup] (
    [GroupId]           VARCHAR (50)  NOT NULL,
    [FirmId]            VARCHAR (10)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserGroup_1] PRIMARY KEY CLUSTERED ([GroupId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserGroupMember]...';


GO
CREATE TABLE [dbo].[UserGroupMember] (
    [GroupAssociationId] UNIQUEIDENTIFIER NOT NULL,
    [GroupId]            VARCHAR (50)     NULL,
    [FirmId]             VARCHAR (10)     NOT NULL,
    [UserId]             VARCHAR (50)     NULL,
    [MemberGroupId]      VARCHAR (50)     NULL,
    [MemberUserId]       VARCHAR (50)     NULL,
    [DynamicAttributes]  VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_UserGroupMember] PRIMARY KEY CLUSTERED ([GroupAssociationId] ASC),
    CONSTRAINT [IX_UserGroupMember] UNIQUE NONCLUSTERED ([FirmId] ASC, [GroupId] ASC, [UserId] ASC, [MemberGroupId] ASC, [MemberUserId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserRole]...';


GO
CREATE TABLE [dbo].[UserRole] (
    [UserId]            VARCHAR (50)  NOT NULL,
    [RoleId]            VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserSession]...';


GO
CREATE TABLE [dbo].[UserSession] (
    [UserId]            VARCHAR (50)  NOT NULL,
    [MachineId]         VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserSession] PRIMARY KEY CLUSTERED ([UserId] ASC, [MachineId] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserSubscription]...';


GO
CREATE TABLE [dbo].[UserSubscription] (
    [SubscriptionId]    UNIQUEIDENTIFIER NOT NULL,
    [UserId]            VARCHAR (50)     NOT NULL,
    [FixEngineId]       VARCHAR (10)     NULL,
    [FixSessionId]      VARCHAR (50)     NULL,
    [DynamicAttributes] VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_UserSubscription] PRIMARY KEY CLUSTERED ([SubscriptionId] ASC),
    CONSTRAINT [IX_UserSubscription] UNIQUE NONCLUSTERED ([UserId] ASC, [FixEngineId] ASC, [FixSessionId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Wheel]...';


GO
CREATE TABLE [dbo].[Wheel] (
    [FirmId]            VARCHAR (10)  NOT NULL,
    [WheelId]           VARCHAR (50)  NOT NULL,
    [DynamicAttributes] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Wheel] PRIMARY KEY NONCLUSTERED ([WheelId] ASC, [FirmId] ASC)
);


GO
PRINT N'Creating Table [dbo].[WheelDestination]...';


GO
CREATE TABLE [dbo].[WheelDestination] (
    [WheelDestinationId] UNIQUEIDENTIFIER NOT NULL,
    [FirmId]             VARCHAR (10)     NOT NULL,
    [WheelId]            VARCHAR (50)     NOT NULL,
    [DestinationId]      VARCHAR (10)     NOT NULL,
    [DestinationCode]    INT              NOT NULL,
    [DynamicAttributes]  VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_WheelDestination] PRIMARY KEY CLUSTERED ([WheelDestinationId] ASC)
);


GO
PRINT N'Creating Index [dbo].[WheelDestination].[IX_WheelDestination]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_WheelDestination]
    ON [dbo].[WheelDestination]([FirmId] ASC, [WheelId] ASC, [DestinationId] ASC, [DestinationCode] ASC);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Task_TaskId]...';


GO
ALTER TABLE [dbo].[Task]
    ADD CONSTRAINT [DF_Task_TaskId] DEFAULT (newid()) FOR [TaskId];


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountDestination_Account]...';


GO
ALTER TABLE [dbo].[AccountDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountDestination_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountDestination_FirmDestination]...';


GO
ALTER TABLE [dbo].[AccountDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountDestination_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountGroup_Firm]...';


GO
ALTER TABLE [dbo].[AccountGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountGroup_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountGroupAssociation_Firm]...';


GO
ALTER TABLE [dbo].[AccountGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountGroupAssociation_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountGroupMember_AccountGroup]...';


GO
ALTER TABLE [dbo].[AccountGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountGroupMember_AccountGroup] FOREIGN KEY ([GroupId], [FirmId]) REFERENCES [dbo].[AccountGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountGroupMember_AccountGroup1]...';


GO
ALTER TABLE [dbo].[AccountGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountGroupMember_AccountGroup1] FOREIGN KEY ([MemberGroupId], [FirmId]) REFERENCES [dbo].[AccountGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountGroupAssociation_AccountGroupAssociation]...';


GO
ALTER TABLE [dbo].[AccountGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountGroupAssociation_AccountGroupAssociation] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountIOIDestination_IOIFirmDestination]...';


GO
ALTER TABLE [dbo].[AccountIOIDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountIOIDestination_IOIFirmDestination] FOREIGN KEY ([FirmId], [DestinationId]) REFERENCES [dbo].[IOIFirmDestination] ([FirmId], [DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AccountIOIDestination_Account]...';


GO
ALTER TABLE [dbo].[AccountIOIDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_AccountIOIDestination_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ACTSettings_Firm]...';


GO
ALTER TABLE [dbo].[ACTSettings] WITH NOCHECK
    ADD CONSTRAINT [FK_ACTSettings_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategy_Firm]...';


GO
ALTER TABLE [dbo].[AlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategy_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategy_AlgoTemplate]...';


GO
ALTER TABLE [dbo].[AlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategy_AlgoTemplate] FOREIGN KEY ([FirmId], [AlgoSuiteId]) REFERENCES [dbo].[AlgoSuite] ([FirmId], [AlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategy_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[AlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategy_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategy_InAlgoStrategy]...';


GO
ALTER TABLE [dbo].[AlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategy_InAlgoStrategy] FOREIGN KEY ([InStrategyId], [InAlgoSuiteId]) REFERENCES [dbo].[InAlgoStrategy] ([InStrategyId], [InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategy_FirmDestination]...';


GO
ALTER TABLE [dbo].[AlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategy_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoSuite_Firm]...';


GO
ALTER TABLE [dbo].[AlgoSuite] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoSuite_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoSuite_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[AlgoSuite] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoSuite_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoStrategyTagMap_AlgoStrategy]...';


GO
ALTER TABLE [dbo].[AlgoTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoStrategyTagMap_AlgoStrategy] FOREIGN KEY ([AlgoStrategyId]) REFERENCES [dbo].[AlgoStrategy] ([AlgoStrategyId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoTagMap_InAlgoStrategyTagMap]...';


GO
ALTER TABLE [dbo].[AlgoTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoTagMap_InAlgoStrategyTagMap] FOREIGN KEY ([InAlgoStrategyTagMapId]) REFERENCES [dbo].[InAlgoStrategyTagMap] ([InAlgoStrategyTagMapId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelStrategy_Firm]...';


GO
ALTER TABLE [dbo].[AlgoWheelStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelStrategy_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelStrategy_FirmDestination]...';


GO
ALTER TABLE [dbo].[AlgoWheelStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelStrategy_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelStrategy_AlgoWheelSuite]...';


GO
ALTER TABLE [dbo].[AlgoWheelStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelStrategy_AlgoWheelSuite] FOREIGN KEY ([FirmId], [AlgoWheelSuiteId]) REFERENCES [dbo].[AlgoWheelSuite] ([FirmId], [AlgoWheelSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelSuite_Firm]...';


GO
ALTER TABLE [dbo].[AlgoWheelSuite] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelSuite_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelSuite_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[AlgoWheelSuite] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelSuite_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelSuite_InAlgoStrategy]...';


GO
ALTER TABLE [dbo].[AlgoWheelSuite] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelSuite_InAlgoStrategy] FOREIGN KEY ([InStrategyId], [InAlgoSuiteId]) REFERENCES [dbo].[InAlgoStrategy] ([InStrategyId], [InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelTagMap_InAlgoStrategyTagMap]...';


GO
ALTER TABLE [dbo].[AlgoWheelTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelTagMap_InAlgoStrategyTagMap] FOREIGN KEY ([InAlgoStrategyTagMapId]) REFERENCES [dbo].[InAlgoStrategyTagMap] ([InAlgoStrategyTagMapId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AlgoWheelStrategyTagMap_AlgoWheelStrategy]...';


GO
ALTER TABLE [dbo].[AlgoWheelTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_AlgoWheelStrategyTagMap_AlgoWheelStrategy] FOREIGN KEY ([AlgoWheelStrategyId]) REFERENCES [dbo].[AlgoWheelStrategy] ([AlgoWheelStrategyId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppInstance_App]...';


GO
ALTER TABLE [dbo].[AppInstance] WITH NOCHECK
    ADD CONSTRAINT [FK_AppInstance_App] FOREIGN KEY ([AppId]) REFERENCES [dbo].[App] ([AppId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUpdate_AppVersion]...';


GO
ALTER TABLE [dbo].[AppUpdate] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUpdate_AppVersion] FOREIGN KEY ([ProductId], [Version]) REFERENCES [dbo].[AppVersion] ([ProductId], [Version]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserFixSubscription_AppUser]...';


GO
ALTER TABLE [dbo].[AppUserFixSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserFixSubscription_AppUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AppUser] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserFixSubscription_FixSession]...';


GO
ALTER TABLE [dbo].[AppUserFixSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserFixSubscription_FixSession] FOREIGN KEY ([FixSessionId]) REFERENCES [dbo].[FixSession] ([FixSessionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserFixSubscription_FixSessionGroup]...';


GO
ALTER TABLE [dbo].[AppUserFixSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserFixSubscription_FixSessionGroup] FOREIGN KEY ([FixSessionGroupId]) REFERENCES [dbo].[FixSessionGroup] ([GroupId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserSubscription_AppUser]...';


GO
ALTER TABLE [dbo].[AppUserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserSubscription_AppUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AppUser] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserSubscription_FirmGroup]...';


GO
ALTER TABLE [dbo].[AppUserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserSubscription_FirmGroup] FOREIGN KEY ([FirmGroupId]) REFERENCES [dbo].[FirmGroup] ([GroupId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserSubscription_Role]...';


GO
ALTER TABLE [dbo].[AppUserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserSubscription_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AppUserSubscription_Firm]...';


GO
ALTER TABLE [dbo].[AppUserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_AppUserSubscription_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Book_Firm]...';


GO
ALTER TABLE [dbo].[Book] WITH NOCHECK
    ADD CONSTRAINT [FK_Book_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Book_ParentBook]...';


GO
ALTER TABLE [dbo].[Book] WITH NOCHECK
    ADD CONSTRAINT [FK_Book_ParentBook] FOREIGN KEY ([FirmId], [ParentBookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookGroup_BookGroup]...';


GO
ALTER TABLE [dbo].[BookGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_BookGroup_BookGroup] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookGroupMember_Firm]...';


GO
ALTER TABLE [dbo].[BookGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookGroupMember_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookGroupMember_Book]...';


GO
ALTER TABLE [dbo].[BookGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookGroupMember_Book] FOREIGN KEY ([FirmId], [BookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookGroupMember_BookGroup]...';


GO
ALTER TABLE [dbo].[BookGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookGroupMember_BookGroup] FOREIGN KEY ([BookGroupId], [FirmId]) REFERENCES [dbo].[BookGroup] ([BookGroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookGroupMember_BookGroup1]...';


GO
ALTER TABLE [dbo].[BookGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookGroupMember_BookGroup1] FOREIGN KEY ([BookGroupId], [FirmId]) REFERENCES [dbo].[BookGroup] ([BookGroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookMember_Firm]...';


GO
ALTER TABLE [dbo].[BookMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookMember_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookMember_Book]...';


GO
ALTER TABLE [dbo].[BookMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookMember_Book] FOREIGN KEY ([FirmId], [ParentBookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_BookMember_Book1]...';


GO
ALTER TABLE [dbo].[BookMember] WITH NOCHECK
    ADD CONSTRAINT [FK_BookMember_Book1] FOREIGN KEY ([FirmId], [ChildBookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ChatGroup_Firm]...';


GO
ALTER TABLE [dbo].[ChatGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_ChatGroup_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ChatGroupMember_ChatGroup]...';


GO
ALTER TABLE [dbo].[ChatGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_ChatGroupMember_ChatGroup] FOREIGN KEY ([GroupId], [FirmId]) REFERENCES [dbo].[ChatGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ChatGroupMember_User]...';


GO
ALTER TABLE [dbo].[ChatGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_ChatGroupMember_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommRule_CommRuleset]...';


GO
ALTER TABLE [dbo].[CommRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CommRule_CommRuleset] FOREIGN KEY ([RulesetId], [FirmId]) REFERENCES [dbo].[CommRuleset] ([RulesetId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommRule_CommSchedule]...';


GO
ALTER TABLE [dbo].[CommRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CommRule_CommSchedule] FOREIGN KEY ([ScheduleId], [FirmId]) REFERENCES [dbo].[CommSchedule] ([ScheduleId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommRulesetAccount_CommRuleset]...';


GO
ALTER TABLE [dbo].[CommRulesetAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_CommRulesetAccount_CommRuleset] FOREIGN KEY ([RulesetId], [FirmId]) REFERENCES [dbo].[CommRuleset] ([RulesetId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommRulesetAccount_Account]...';


GO
ALTER TABLE [dbo].[CommRulesetAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_CommRulesetAccount_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommRulesetAccount_SubAccount]...';


GO
ALTER TABLE [dbo].[CommRulesetAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_CommRulesetAccount_SubAccount] FOREIGN KEY ([SubAccountId], [AccountId], [FirmId]) REFERENCES [dbo].[SubAccount] ([SubAccountId], [AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CommSchedule_Firm]...';


GO
ALTER TABLE [dbo].[CommSchedule] WITH NOCHECK
    ADD CONSTRAINT [FK_CommSchedule_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_AlgoSuite]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_AlgoSuite] FOREIGN KEY ([FirmId], [AlgoSuiteId]) REFERENCES [dbo].[AlgoSuite] ([FirmId], [AlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_Wheel]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_Wheel] FOREIGN KEY ([WheelId], [FirmId]) REFERENCES [dbo].[Wheel] ([WheelId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_FirmDestination]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_FirmDestination1]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_FirmDestination1] FOREIGN KEY ([FirmId], [BackupDestinationId], [BackupDestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_AlgoWheelSuite]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_AlgoWheelSuite] FOREIGN KEY ([FirmId], [AlgoWheelSuiteId]) REFERENCES [dbo].[AlgoWheelSuite] ([FirmId], [AlgoWheelSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_CustomerRoutingRule_FirmDestination2]...';


GO
ALTER TABLE [dbo].[CustomerRoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_CustomerRoutingRule_FirmDestination2] FOREIGN KEY ([FirmId], [FracDestinationId], [FracDestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ETBFirmList_ETBFirmList]...';


GO
ALTER TABLE [dbo].[ETBFirmList] WITH NOCHECK
    ADD CONSTRAINT [FK_ETBFirmList_ETBFirmList] FOREIGN KEY ([ETBListId]) REFERENCES [dbo].[ETBList] ([ETBListId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ETBFirmList_Firm]...';


GO
ALTER TABLE [dbo].[ETBFirmList] WITH NOCHECK
    ADD CONSTRAINT [FK_ETBFirmList_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Firm_ETBList]...';


GO
ALTER TABLE [dbo].[Firm] WITH NOCHECK
    ADD CONSTRAINT [FK_Firm_ETBList] FOREIGN KEY ([ETBListId]) REFERENCES [dbo].[ETBList] ([ETBListId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Firm_Role]...';


GO
ALTER TABLE [dbo].[Firm] WITH NOCHECK
    ADD CONSTRAINT [FK_Firm_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Firm_Firm]...';


GO
ALTER TABLE [dbo].[Firm] WITH NOCHECK
    ADD CONSTRAINT [FK_Firm_Firm] FOREIGN KEY ([ParentFirm]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestination_ProtectedQuotes]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestination_ProtectedQuotes] FOREIGN KEY ([ProtectedQuoteId]) REFERENCES [dbo].[ProtectedQuotes] ([Code]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestination_RFQ]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestination_RFQ] FOREIGN KEY ([FirmId], [RFQFirmDestinationId]) REFERENCES [dbo].[RFQFirmDestination] ([FirmId], [DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestinations_Destination]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestinations_Destination] FOREIGN KEY ([DestinationId]) REFERENCES [dbo].[Destination] ([DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestinations_Firm]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestinations_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestination_Country]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestination_Country] FOREIGN KEY ([ExchangeCode]) REFERENCES [dbo].[Country] ([Code]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmDestination_FixSession]...';


GO
ALTER TABLE [dbo].[FirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmDestination_FixSession] FOREIGN KEY ([FixSessionId]) REFERENCES [dbo].[FixSession] ([FixSessionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmGroupMember_Firm]...';


GO
ALTER TABLE [dbo].[FirmGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmGroupMember_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmGroupMember_FirmGroup]...';


GO
ALTER TABLE [dbo].[FirmGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmGroupMember_FirmGroup] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[FirmGroup] ([GroupId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmRiskSetting_Firm]...';


GO
ALTER TABLE [dbo].[FirmRiskSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmRiskSetting_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmSetting_Firm]...';


GO
ALTER TABLE [dbo].[FirmSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmSetting_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmSubscription_Firm]...';


GO
ALTER TABLE [dbo].[FirmSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmSubscription_Firm] FOREIGN KEY ([PrimaryFirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FirmSubscription_Firm1]...';


GO
ALTER TABLE [dbo].[FirmSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_FirmSubscription_Firm1] FOREIGN KEY ([SubFirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FixSessionGroupMember_FixSession]...';


GO
ALTER TABLE [dbo].[FixSessionGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_FixSessionGroupMember_FixSession] FOREIGN KEY ([FixSessionId]) REFERENCES [dbo].[FixSession] ([FixSessionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_FixSessionGroupMember_FixSessionGroup]...';


GO
ALTER TABLE [dbo].[FixSessionGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_FixSessionGroupMember_FixSessionGroup] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[FixSessionGroup] ([GroupId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Holiday_Country]...';


GO
ALTER TABLE [dbo].[Holiday] WITH NOCHECK
    ADD CONSTRAINT [FK_Holiday_Country] FOREIGN KEY ([Calendar]) REFERENCES [dbo].[Country] ([Code]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoFirmSubscription_Firm]...';


GO
ALTER TABLE [dbo].[InAlgoFirmSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoFirmSubscription_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoFirmSubscription_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[InAlgoFirmSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoFirmSubscription_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoStrategy_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[InAlgoStrategy] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoStrategy_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoStrategyTagMap_InAlgoTag]...';


GO
ALTER TABLE [dbo].[InAlgoStrategyTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoStrategyTagMap_InAlgoTag] FOREIGN KEY ([InAlgoTagId]) REFERENCES [dbo].[InAlgoTag] ([InAlgoTagId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoStrategyTagMap_InAlgoStrategy]...';


GO
ALTER TABLE [dbo].[InAlgoStrategyTagMap] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoStrategyTagMap_InAlgoStrategy] FOREIGN KEY ([InStrategyId], [InAlgoSuiteId]) REFERENCES [dbo].[InAlgoStrategy] ([InStrategyId], [InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InAlgoTag_InAlgoSuite]...';


GO
ALTER TABLE [dbo].[InAlgoTag] WITH NOCHECK
    ADD CONSTRAINT [FK_InAlgoTag_InAlgoSuite] FOREIGN KEY ([InAlgoSuiteId]) REFERENCES [dbo].[InAlgoSuite] ([InAlgoSuiteId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOICustomerGroup_Firm]...';


GO
ALTER TABLE [dbo].[IOICustomerGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_IOICustomerGroup_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOICustomerGroupMember_IOICustomerGroup]...';


GO
ALTER TABLE [dbo].[IOICustomerGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_IOICustomerGroupMember_IOICustomerGroup] FOREIGN KEY ([FirmId], [GroupId]) REFERENCES [dbo].[IOICustomerGroup] ([FirmId], [GroupId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOICustomerGroupMember_Account]...';


GO
ALTER TABLE [dbo].[IOICustomerGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_IOICustomerGroupMember_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOIFirmDestination_Destination]...';


GO
ALTER TABLE [dbo].[IOIFirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_IOIFirmDestination_Destination] FOREIGN KEY ([DestinationId]) REFERENCES [dbo].[Destination] ([DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOIFirmDestination_Firm]...';


GO
ALTER TABLE [dbo].[IOIFirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_IOIFirmDestination_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_IOISettings_Firm]...';


GO
ALTER TABLE [dbo].[IOISettings] WITH NOCHECK
    ADD CONSTRAINT [FK_IOISettings_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MarketMaker_Book]...';


GO
ALTER TABLE [dbo].[MarketMaker] WITH NOCHECK
    ADD CONSTRAINT [FK_MarketMaker_Book] FOREIGN KEY ([FirmId], [BookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MarketMaker_Account]...';


GO
ALTER TABLE [dbo].[MarketMaker] WITH NOCHECK
    ADD CONSTRAINT [FK_MarketMaker_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MarketMaker_User]...';


GO
ALTER TABLE [dbo].[MarketMaker] WITH NOCHECK
    ADD CONSTRAINT [FK_MarketMaker_User] FOREIGN KEY ([FirmId], [LoginId]) REFERENCES [dbo].[User] ([FirmId], [LoginId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PriceBand_Firm]...';


GO
ALTER TABLE [dbo].[PriceBand] WITH NOCHECK
    ADD CONSTRAINT [FK_PriceBand_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PriceProfile_Firm]...';


GO
ALTER TABLE [dbo].[PriceProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_PriceProfile_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PriceProfileBand_PriceProfile]...';


GO
ALTER TABLE [dbo].[PriceProfileBand] WITH NOCHECK
    ADD CONSTRAINT [FK_PriceProfileBand_PriceProfile] FOREIGN KEY ([PriceProfileId]) REFERENCES [dbo].[PriceProfile] ([PriceProfileId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PriceProfileBand_Firm]...';


GO
ALTER TABLE [dbo].[PriceProfileBand] WITH NOCHECK
    ADD CONSTRAINT [FK_PriceProfileBand_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Report_Firm]...';


GO
ALTER TABLE [dbo].[Report] WITH NOCHECK
    ADD CONSTRAINT [FK_Report_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Report_ReportTemplate]...';


GO
ALTER TABLE [dbo].[Report] WITH NOCHECK
    ADD CONSTRAINT [FK_Report_ReportTemplate] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[ReportTemplate] ([TemplateId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Report_ReportConfig]...';


GO
ALTER TABLE [dbo].[Report] WITH NOCHECK
    ADD CONSTRAINT [FK_Report_ReportConfig] FOREIGN KEY ([ReportType]) REFERENCES [dbo].[ReportConfig] ([ReportTypeNo]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReportDetail_ReportTemplate]...';


GO
ALTER TABLE [dbo].[ReportDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_ReportDetail_ReportTemplate] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[ReportTemplate] ([TemplateId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReportDetail_Firm]...';


GO
ALTER TABLE [dbo].[ReportDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_ReportDetail_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReportDetail_Report]...';


GO
ALTER TABLE [dbo].[ReportDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_ReportDetail_Report] FOREIGN KEY ([ReportId]) REFERENCES [dbo].[Report] ([ReportId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReportTemplate_ReportConfig]...';


GO
ALTER TABLE [dbo].[ReportTemplate] WITH NOCHECK
    ADD CONSTRAINT [FK_ReportTemplate_ReportConfig] FOREIGN KEY ([ReportType]) REFERENCES [dbo].[ReportConfig] ([ReportTypeNo]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RFQFirmDestination_Destination]...';


GO
ALTER TABLE [dbo].[RFQFirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_RFQFirmDestination_Destination] FOREIGN KEY ([DestinationId]) REFERENCES [dbo].[Destination] ([DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RFQFirmDestination_Firm]...';


GO
ALTER TABLE [dbo].[RFQFirmDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_RFQFirmDestination_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RiskLimit_PriceProfile]...';


GO
ALTER TABLE [dbo].[RiskLimit] WITH NOCHECK
    ADD CONSTRAINT [FK_RiskLimit_PriceProfile] FOREIGN KEY ([PriceProfileId]) REFERENCES [dbo].[PriceProfile] ([PriceProfileId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RiskLimit_User]...';


GO
ALTER TABLE [dbo].[RiskLimit] WITH NOCHECK
    ADD CONSTRAINT [FK_RiskLimit_User] FOREIGN KEY ([FirmId], [TraderId]) REFERENCES [dbo].[User] ([FirmId], [LoginId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RiskLimit_Firm]...';


GO
ALTER TABLE [dbo].[RiskLimit] WITH NOCHECK
    ADD CONSTRAINT [FK_RiskLimit_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RiskLimit_Account]...';


GO
ALTER TABLE [dbo].[RiskLimit] WITH NOCHECK
    ADD CONSTRAINT [FK_RiskLimit_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RoutingRule_Destination]...';


GO
ALTER TABLE [dbo].[RoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoutingRule_Destination] FOREIGN KEY ([DestinationId]) REFERENCES [dbo].[Destination] ([DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RoutingRule_FirmDestination]...';


GO
ALTER TABLE [dbo].[RoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoutingRule_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RoutingRule_Firm]...';


GO
ALTER TABLE [dbo].[RoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoutingRule_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RoutingRule_FixSession]...';


GO
ALTER TABLE [dbo].[RoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoutingRule_FixSession] FOREIGN KEY ([FixSessionId]) REFERENCES [dbo].[FixSession] ([FixSessionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RoutingRule_IOIFirmDestination]...';


GO
ALTER TABLE [dbo].[RoutingRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RoutingRule_IOIFirmDestination] FOREIGN KEY ([FirmId], [IOIDestinationId]) REFERENCES [dbo].[IOIFirmDestination] ([FirmId], [DestinationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RSPRule_Firm]...';


GO
ALTER TABLE [dbo].[RSPCustomerRule] WITH NOCHECK
    ADD CONSTRAINT [FK_RSPRule_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RSPRuleAccount_Firm]...';


GO
ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_RSPRuleAccount_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RSPRuleAccount_RSPRule]...';


GO
ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_RSPRuleAccount_RSPRule] FOREIGN KEY ([RSPRuleId], [FirmId]) REFERENCES [dbo].[RSPCustomerRule] ([RSPRuleId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_RSPRuleAccount_Account]...';


GO
ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_RSPRuleAccount_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SSOConfig_Firm]...';


GO
ALTER TABLE [dbo].[SSOConfig] WITH NOCHECK
    ADD CONSTRAINT [FK_SSOConfig_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_StockConfig_Firm]...';


GO
ALTER TABLE [dbo].[StockConfig] WITH NOCHECK
    ADD CONSTRAINT [FK_StockConfig_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_StockConfig_User1]...';


GO
ALTER TABLE [dbo].[StockConfig] WITH NOCHECK
    ADD CONSTRAINT [FK_StockConfig_User1] FOREIGN KEY ([FirmId], [LoginId]) REFERENCES [dbo].[User] ([FirmId], [LoginId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SubAccount_Account]...';


GO
ALTER TABLE [dbo].[SubAccount] WITH NOCHECK
    ADD CONSTRAINT [FK_SubAccount_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Task_ScheduledJob]...';


GO
ALTER TABLE [dbo].[Task] WITH NOCHECK
    ADD CONSTRAINT [FK_Task_ScheduledJob] FOREIGN KEY ([JobId]) REFERENCES [dbo].[ScheduledJob] ([JobId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TradeTemplate_Firm]...';


GO
ALTER TABLE [dbo].[TradeTemplate] WITH NOCHECK
    ADD CONSTRAINT [FK_TradeTemplate_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_User_Role]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_User_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_User_Firm]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_User_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_User_Book]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_User_Book] FOREIGN KEY ([FirmId], [BookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderToAccountAssociation_User]...';


GO
ALTER TABLE [dbo].[UserAccounts] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderToAccountAssociation_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserAccounts_AccountGroup]...';


GO
ALTER TABLE [dbo].[UserAccounts] WITH NOCHECK
    ADD CONSTRAINT [FK_UserAccounts_AccountGroup] FOREIGN KEY ([GroupId], [FirmId]) REFERENCES [dbo].[AccountGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderToAccountAssociation_Firm]...';


GO
ALTER TABLE [dbo].[UserAccounts] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderToAccountAssociation_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderToAccountAssociation_Account]...';


GO
ALTER TABLE [dbo].[UserAccounts] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderToAccountAssociation_Account] FOREIGN KEY ([AccountId], [FirmId]) REFERENCES [dbo].[Account] ([AccountId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserBook_Firm]...';


GO
ALTER TABLE [dbo].[UserBook] WITH NOCHECK
    ADD CONSTRAINT [FK_UserBook_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserBook_Book]...';


GO
ALTER TABLE [dbo].[UserBook] WITH NOCHECK
    ADD CONSTRAINT [FK_UserBook_Book] FOREIGN KEY ([FirmId], [BookId]) REFERENCES [dbo].[Book] ([FirmId], [BookId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserBook_User]...';


GO
ALTER TABLE [dbo].[UserBook] WITH NOCHECK
    ADD CONSTRAINT [FK_UserBook_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserBook_UserGroup]...';


GO
ALTER TABLE [dbo].[UserBook] WITH NOCHECK
    ADD CONSTRAINT [FK_UserBook_UserGroup] FOREIGN KEY ([BookGroupId], [FirmId]) REFERENCES [dbo].[BookGroup] ([BookGroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderGroup_Firm]...';


GO
ALTER TABLE [dbo].[UserGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderGroup_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderGroupAssociation_User]...';


GO
ALTER TABLE [dbo].[UserGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderGroupAssociation_User] FOREIGN KEY ([MemberUserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderGroupAssociation_User1]...';


GO
ALTER TABLE [dbo].[UserGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderGroupAssociation_User1] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TraderGroupAssociation_Firm]...';


GO
ALTER TABLE [dbo].[UserGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_TraderGroupAssociation_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserGroupMember_UserGroup]...';


GO
ALTER TABLE [dbo].[UserGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_UserGroupMember_UserGroup] FOREIGN KEY ([GroupId], [FirmId]) REFERENCES [dbo].[UserGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserGroupMember_UserGroup1]...';


GO
ALTER TABLE [dbo].[UserGroupMember] WITH NOCHECK
    ADD CONSTRAINT [FK_UserGroupMember_UserGroup1] FOREIGN KEY ([MemberGroupId], [FirmId]) REFERENCES [dbo].[UserGroup] ([GroupId], [FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserRole_User]...';


GO
ALTER TABLE [dbo].[UserRole] WITH NOCHECK
    ADD CONSTRAINT [FK_UserRole_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserRole_Role]...';


GO
ALTER TABLE [dbo].[UserRole] WITH NOCHECK
    ADD CONSTRAINT [FK_UserRole_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserFixSession_User]...';


GO
ALTER TABLE [dbo].[UserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_UserFixSession_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserFixSession_FixSession]...';


GO
ALTER TABLE [dbo].[UserSubscription] WITH NOCHECK
    ADD CONSTRAINT [FK_UserFixSession_FixSession] FOREIGN KEY ([FixSessionId]) REFERENCES [dbo].[FixSession] ([FixSessionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Wheel_Firm]...';


GO
ALTER TABLE [dbo].[Wheel] WITH NOCHECK
    ADD CONSTRAINT [FK_Wheel_Firm] FOREIGN KEY ([FirmId]) REFERENCES [dbo].[Firm] ([FirmId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WheelDestination_FirmDestination]...';


GO
ALTER TABLE [dbo].[WheelDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_WheelDestination_FirmDestination] FOREIGN KEY ([FirmId], [DestinationId], [DestinationCode]) REFERENCES [dbo].[FirmDestination] ([FirmId], [DestinationId], [DestinationCode]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WheelDestination_Wheel]...';


GO
ALTER TABLE [dbo].[WheelDestination] WITH NOCHECK
    ADD CONSTRAINT [FK_WheelDestination_Wheel] FOREIGN KEY ([WheelId], [FirmId]) REFERENCES [dbo].[Wheel] ([WheelId], [FirmId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[AccountDestination] WITH CHECK CHECK CONSTRAINT [FK_AccountDestination_Account];

ALTER TABLE [dbo].[AccountDestination] WITH CHECK CHECK CONSTRAINT [FK_AccountDestination_FirmDestination];

ALTER TABLE [dbo].[AccountGroup] WITH CHECK CHECK CONSTRAINT [FK_AccountGroup_Firm];

ALTER TABLE [dbo].[AccountGroupMember] WITH CHECK CHECK CONSTRAINT [FK_AccountGroupAssociation_Firm];

ALTER TABLE [dbo].[AccountGroupMember] WITH CHECK CHECK CONSTRAINT [FK_AccountGroupMember_AccountGroup];

ALTER TABLE [dbo].[AccountGroupMember] WITH CHECK CHECK CONSTRAINT [FK_AccountGroupMember_AccountGroup1];

ALTER TABLE [dbo].[AccountGroupMember] WITH CHECK CHECK CONSTRAINT [FK_AccountGroupAssociation_AccountGroupAssociation];

ALTER TABLE [dbo].[AccountIOIDestination] WITH CHECK CHECK CONSTRAINT [FK_AccountIOIDestination_IOIFirmDestination];

ALTER TABLE [dbo].[AccountIOIDestination] WITH CHECK CHECK CONSTRAINT [FK_AccountIOIDestination_Account];

ALTER TABLE [dbo].[ACTSettings] WITH CHECK CHECK CONSTRAINT [FK_ACTSettings_Firm];

ALTER TABLE [dbo].[AlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategy_Firm];

ALTER TABLE [dbo].[AlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategy_AlgoTemplate];

ALTER TABLE [dbo].[AlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategy_InAlgoSuite];

ALTER TABLE [dbo].[AlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategy_InAlgoStrategy];

ALTER TABLE [dbo].[AlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategy_FirmDestination];

ALTER TABLE [dbo].[AlgoSuite] WITH CHECK CHECK CONSTRAINT [FK_AlgoSuite_Firm];

ALTER TABLE [dbo].[AlgoSuite] WITH CHECK CHECK CONSTRAINT [FK_AlgoSuite_InAlgoSuite];

ALTER TABLE [dbo].[AlgoTagMap] WITH CHECK CHECK CONSTRAINT [FK_AlgoStrategyTagMap_AlgoStrategy];

ALTER TABLE [dbo].[AlgoTagMap] WITH CHECK CHECK CONSTRAINT [FK_AlgoTagMap_InAlgoStrategyTagMap];

ALTER TABLE [dbo].[AlgoWheelStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelStrategy_Firm];

ALTER TABLE [dbo].[AlgoWheelStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelStrategy_FirmDestination];

ALTER TABLE [dbo].[AlgoWheelStrategy] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelStrategy_AlgoWheelSuite];

ALTER TABLE [dbo].[AlgoWheelSuite] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelSuite_Firm];

ALTER TABLE [dbo].[AlgoWheelSuite] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelSuite_InAlgoSuite];

ALTER TABLE [dbo].[AlgoWheelSuite] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelSuite_InAlgoStrategy];

ALTER TABLE [dbo].[AlgoWheelTagMap] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelTagMap_InAlgoStrategyTagMap];

ALTER TABLE [dbo].[AlgoWheelTagMap] WITH CHECK CHECK CONSTRAINT [FK_AlgoWheelStrategyTagMap_AlgoWheelStrategy];

ALTER TABLE [dbo].[AppInstance] WITH CHECK CHECK CONSTRAINT [FK_AppInstance_App];

ALTER TABLE [dbo].[AppUpdate] WITH CHECK CHECK CONSTRAINT [FK_AppUpdate_AppVersion];

ALTER TABLE [dbo].[AppUserFixSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserFixSubscription_AppUser];

ALTER TABLE [dbo].[AppUserFixSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserFixSubscription_FixSession];

ALTER TABLE [dbo].[AppUserFixSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserFixSubscription_FixSessionGroup];

ALTER TABLE [dbo].[AppUserSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserSubscription_AppUser];

ALTER TABLE [dbo].[AppUserSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserSubscription_FirmGroup];

ALTER TABLE [dbo].[AppUserSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserSubscription_Role];

ALTER TABLE [dbo].[AppUserSubscription] WITH CHECK CHECK CONSTRAINT [FK_AppUserSubscription_Firm];

ALTER TABLE [dbo].[Book] WITH CHECK CHECK CONSTRAINT [FK_Book_Firm];

ALTER TABLE [dbo].[Book] WITH CHECK CHECK CONSTRAINT [FK_Book_ParentBook];

ALTER TABLE [dbo].[BookGroup] WITH CHECK CHECK CONSTRAINT [FK_BookGroup_BookGroup];

ALTER TABLE [dbo].[BookGroupMember] WITH CHECK CHECK CONSTRAINT [FK_BookGroupMember_Firm];

ALTER TABLE [dbo].[BookGroupMember] WITH CHECK CHECK CONSTRAINT [FK_BookGroupMember_Book];

ALTER TABLE [dbo].[BookGroupMember] WITH CHECK CHECK CONSTRAINT [FK_BookGroupMember_BookGroup];

ALTER TABLE [dbo].[BookGroupMember] WITH CHECK CHECK CONSTRAINT [FK_BookGroupMember_BookGroup1];

ALTER TABLE [dbo].[BookMember] WITH CHECK CHECK CONSTRAINT [FK_BookMember_Firm];

ALTER TABLE [dbo].[BookMember] WITH CHECK CHECK CONSTRAINT [FK_BookMember_Book];

ALTER TABLE [dbo].[BookMember] WITH CHECK CHECK CONSTRAINT [FK_BookMember_Book1];

ALTER TABLE [dbo].[ChatGroup] WITH CHECK CHECK CONSTRAINT [FK_ChatGroup_Firm];

ALTER TABLE [dbo].[ChatGroupMember] WITH CHECK CHECK CONSTRAINT [FK_ChatGroupMember_ChatGroup];

ALTER TABLE [dbo].[ChatGroupMember] WITH CHECK CHECK CONSTRAINT [FK_ChatGroupMember_User];

ALTER TABLE [dbo].[CommRule] WITH CHECK CHECK CONSTRAINT [FK_CommRule_CommRuleset];

ALTER TABLE [dbo].[CommRule] WITH CHECK CHECK CONSTRAINT [FK_CommRule_CommSchedule];

ALTER TABLE [dbo].[CommRulesetAccount] WITH CHECK CHECK CONSTRAINT [FK_CommRulesetAccount_CommRuleset];

ALTER TABLE [dbo].[CommRulesetAccount] WITH CHECK CHECK CONSTRAINT [FK_CommRulesetAccount_Account];

ALTER TABLE [dbo].[CommRulesetAccount] WITH CHECK CHECK CONSTRAINT [FK_CommRulesetAccount_SubAccount];

ALTER TABLE [dbo].[CommSchedule] WITH CHECK CHECK CONSTRAINT [FK_CommSchedule_Firm];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_AlgoSuite];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_Wheel];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_FirmDestination];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_FirmDestination1];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_AlgoWheelSuite];

ALTER TABLE [dbo].[CustomerRoutingRule] WITH CHECK CHECK CONSTRAINT [FK_CustomerRoutingRule_FirmDestination2];

ALTER TABLE [dbo].[ETBFirmList] WITH CHECK CHECK CONSTRAINT [FK_ETBFirmList_ETBFirmList];

ALTER TABLE [dbo].[ETBFirmList] WITH CHECK CHECK CONSTRAINT [FK_ETBFirmList_Firm];

ALTER TABLE [dbo].[Firm] WITH CHECK CHECK CONSTRAINT [FK_Firm_ETBList];

ALTER TABLE [dbo].[Firm] WITH CHECK CHECK CONSTRAINT [FK_Firm_Role];

ALTER TABLE [dbo].[Firm] WITH CHECK CHECK CONSTRAINT [FK_Firm_Firm];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestination_ProtectedQuotes];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestination_RFQ];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestinations_Destination];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestinations_Firm];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestination_Country];

ALTER TABLE [dbo].[FirmDestination] WITH CHECK CHECK CONSTRAINT [FK_FirmDestination_FixSession];

ALTER TABLE [dbo].[FirmGroupMember] WITH CHECK CHECK CONSTRAINT [FK_FirmGroupMember_Firm];

ALTER TABLE [dbo].[FirmGroupMember] WITH CHECK CHECK CONSTRAINT [FK_FirmGroupMember_FirmGroup];

ALTER TABLE [dbo].[FirmRiskSetting] WITH CHECK CHECK CONSTRAINT [FK_FirmRiskSetting_Firm];

ALTER TABLE [dbo].[FirmSetting] WITH CHECK CHECK CONSTRAINT [FK_FirmSetting_Firm];

ALTER TABLE [dbo].[FirmSubscription] WITH CHECK CHECK CONSTRAINT [FK_FirmSubscription_Firm];

ALTER TABLE [dbo].[FirmSubscription] WITH CHECK CHECK CONSTRAINT [FK_FirmSubscription_Firm1];

ALTER TABLE [dbo].[FixSessionGroupMember] WITH CHECK CHECK CONSTRAINT [FK_FixSessionGroupMember_FixSession];

ALTER TABLE [dbo].[FixSessionGroupMember] WITH CHECK CHECK CONSTRAINT [FK_FixSessionGroupMember_FixSessionGroup];

ALTER TABLE [dbo].[Holiday] WITH CHECK CHECK CONSTRAINT [FK_Holiday_Country];

ALTER TABLE [dbo].[InAlgoFirmSubscription] WITH CHECK CHECK CONSTRAINT [FK_InAlgoFirmSubscription_Firm];

ALTER TABLE [dbo].[InAlgoFirmSubscription] WITH CHECK CHECK CONSTRAINT [FK_InAlgoFirmSubscription_InAlgoSuite];

ALTER TABLE [dbo].[InAlgoStrategy] WITH CHECK CHECK CONSTRAINT [FK_InAlgoStrategy_InAlgoSuite];

ALTER TABLE [dbo].[InAlgoStrategyTagMap] WITH CHECK CHECK CONSTRAINT [FK_InAlgoStrategyTagMap_InAlgoTag];

ALTER TABLE [dbo].[InAlgoStrategyTagMap] WITH CHECK CHECK CONSTRAINT [FK_InAlgoStrategyTagMap_InAlgoStrategy];

ALTER TABLE [dbo].[InAlgoTag] WITH CHECK CHECK CONSTRAINT [FK_InAlgoTag_InAlgoSuite];

ALTER TABLE [dbo].[IOICustomerGroup] WITH CHECK CHECK CONSTRAINT [FK_IOICustomerGroup_Firm];

ALTER TABLE [dbo].[IOICustomerGroupMember] WITH CHECK CHECK CONSTRAINT [FK_IOICustomerGroupMember_IOICustomerGroup];

ALTER TABLE [dbo].[IOICustomerGroupMember] WITH CHECK CHECK CONSTRAINT [FK_IOICustomerGroupMember_Account];

ALTER TABLE [dbo].[IOIFirmDestination] WITH CHECK CHECK CONSTRAINT [FK_IOIFirmDestination_Destination];

ALTER TABLE [dbo].[IOIFirmDestination] WITH CHECK CHECK CONSTRAINT [FK_IOIFirmDestination_Firm];

ALTER TABLE [dbo].[IOISettings] WITH CHECK CHECK CONSTRAINT [FK_IOISettings_Firm];

ALTER TABLE [dbo].[MarketMaker] WITH CHECK CHECK CONSTRAINT [FK_MarketMaker_Book];

ALTER TABLE [dbo].[MarketMaker] WITH CHECK CHECK CONSTRAINT [FK_MarketMaker_Account];

ALTER TABLE [dbo].[MarketMaker] WITH CHECK CHECK CONSTRAINT [FK_MarketMaker_User];

ALTER TABLE [dbo].[PriceBand] WITH CHECK CHECK CONSTRAINT [FK_PriceBand_Firm];

ALTER TABLE [dbo].[PriceProfile] WITH CHECK CHECK CONSTRAINT [FK_PriceProfile_Firm];

ALTER TABLE [dbo].[PriceProfileBand] WITH CHECK CHECK CONSTRAINT [FK_PriceProfileBand_PriceProfile];

ALTER TABLE [dbo].[PriceProfileBand] WITH CHECK CHECK CONSTRAINT [FK_PriceProfileBand_Firm];

ALTER TABLE [dbo].[Report] WITH CHECK CHECK CONSTRAINT [FK_Report_Firm];

ALTER TABLE [dbo].[Report] WITH CHECK CHECK CONSTRAINT [FK_Report_ReportTemplate];

ALTER TABLE [dbo].[Report] WITH CHECK CHECK CONSTRAINT [FK_Report_ReportConfig];

ALTER TABLE [dbo].[ReportDetail] WITH CHECK CHECK CONSTRAINT [FK_ReportDetail_ReportTemplate];

ALTER TABLE [dbo].[ReportDetail] WITH CHECK CHECK CONSTRAINT [FK_ReportDetail_Firm];

ALTER TABLE [dbo].[ReportDetail] WITH CHECK CHECK CONSTRAINT [FK_ReportDetail_Report];

ALTER TABLE [dbo].[ReportTemplate] WITH CHECK CHECK CONSTRAINT [FK_ReportTemplate_ReportConfig];

ALTER TABLE [dbo].[RFQFirmDestination] WITH CHECK CHECK CONSTRAINT [FK_RFQFirmDestination_Destination];

ALTER TABLE [dbo].[RFQFirmDestination] WITH CHECK CHECK CONSTRAINT [FK_RFQFirmDestination_Firm];

ALTER TABLE [dbo].[RiskLimit] WITH CHECK CHECK CONSTRAINT [FK_RiskLimit_PriceProfile];

ALTER TABLE [dbo].[RiskLimit] WITH CHECK CHECK CONSTRAINT [FK_RiskLimit_User];

ALTER TABLE [dbo].[RiskLimit] WITH CHECK CHECK CONSTRAINT [FK_RiskLimit_Firm];

ALTER TABLE [dbo].[RiskLimit] WITH CHECK CHECK CONSTRAINT [FK_RiskLimit_Account];

ALTER TABLE [dbo].[RoutingRule] WITH CHECK CHECK CONSTRAINT [FK_RoutingRule_Destination];

ALTER TABLE [dbo].[RoutingRule] WITH CHECK CHECK CONSTRAINT [FK_RoutingRule_FirmDestination];

ALTER TABLE [dbo].[RoutingRule] WITH CHECK CHECK CONSTRAINT [FK_RoutingRule_Firm];

ALTER TABLE [dbo].[RoutingRule] WITH CHECK CHECK CONSTRAINT [FK_RoutingRule_FixSession];

ALTER TABLE [dbo].[RoutingRule] WITH CHECK CHECK CONSTRAINT [FK_RoutingRule_IOIFirmDestination];

ALTER TABLE [dbo].[RSPCustomerRule] WITH CHECK CHECK CONSTRAINT [FK_RSPRule_Firm];

ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH CHECK CHECK CONSTRAINT [FK_RSPRuleAccount_Firm];

ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH CHECK CHECK CONSTRAINT [FK_RSPRuleAccount_RSPRule];

ALTER TABLE [dbo].[RSPCustomerRuleAccount] WITH CHECK CHECK CONSTRAINT [FK_RSPRuleAccount_Account];

ALTER TABLE [dbo].[SSOConfig] WITH CHECK CHECK CONSTRAINT [FK_SSOConfig_Firm];

ALTER TABLE [dbo].[StockConfig] WITH CHECK CHECK CONSTRAINT [FK_StockConfig_Firm];

ALTER TABLE [dbo].[StockConfig] WITH CHECK CHECK CONSTRAINT [FK_StockConfig_User1];

ALTER TABLE [dbo].[SubAccount] WITH CHECK CHECK CONSTRAINT [FK_SubAccount_Account];

ALTER TABLE [dbo].[Task] WITH CHECK CHECK CONSTRAINT [FK_Task_ScheduledJob];

ALTER TABLE [dbo].[TradeTemplate] WITH CHECK CHECK CONSTRAINT [FK_TradeTemplate_Firm];

ALTER TABLE [dbo].[User] WITH CHECK CHECK CONSTRAINT [FK_User_Role];

ALTER TABLE [dbo].[User] WITH CHECK CHECK CONSTRAINT [FK_User_Firm];

ALTER TABLE [dbo].[User] WITH CHECK CHECK CONSTRAINT [FK_User_Book];

ALTER TABLE [dbo].[UserAccounts] WITH CHECK CHECK CONSTRAINT [FK_TraderToAccountAssociation_User];

ALTER TABLE [dbo].[UserAccounts] WITH CHECK CHECK CONSTRAINT [FK_UserAccounts_AccountGroup];

ALTER TABLE [dbo].[UserAccounts] WITH CHECK CHECK CONSTRAINT [FK_TraderToAccountAssociation_Firm];

ALTER TABLE [dbo].[UserAccounts] WITH CHECK CHECK CONSTRAINT [FK_TraderToAccountAssociation_Account];

ALTER TABLE [dbo].[UserBook] WITH CHECK CHECK CONSTRAINT [FK_UserBook_Firm];

ALTER TABLE [dbo].[UserBook] WITH CHECK CHECK CONSTRAINT [FK_UserBook_Book];

ALTER TABLE [dbo].[UserBook] WITH CHECK CHECK CONSTRAINT [FK_UserBook_User];

ALTER TABLE [dbo].[UserBook] WITH CHECK CHECK CONSTRAINT [FK_UserBook_UserGroup];

ALTER TABLE [dbo].[UserGroup] WITH CHECK CHECK CONSTRAINT [FK_TraderGroup_Firm];

ALTER TABLE [dbo].[UserGroupMember] WITH CHECK CHECK CONSTRAINT [FK_TraderGroupAssociation_User];

ALTER TABLE [dbo].[UserGroupMember] WITH CHECK CHECK CONSTRAINT [FK_TraderGroupAssociation_User1];

ALTER TABLE [dbo].[UserGroupMember] WITH CHECK CHECK CONSTRAINT [FK_TraderGroupAssociation_Firm];

ALTER TABLE [dbo].[UserGroupMember] WITH CHECK CHECK CONSTRAINT [FK_UserGroupMember_UserGroup];

ALTER TABLE [dbo].[UserGroupMember] WITH CHECK CHECK CONSTRAINT [FK_UserGroupMember_UserGroup1];

ALTER TABLE [dbo].[UserRole] WITH CHECK CHECK CONSTRAINT [FK_UserRole_User];

ALTER TABLE [dbo].[UserRole] WITH CHECK CHECK CONSTRAINT [FK_UserRole_Role];

ALTER TABLE [dbo].[UserSubscription] WITH CHECK CHECK CONSTRAINT [FK_UserFixSession_User];

ALTER TABLE [dbo].[UserSubscription] WITH CHECK CHECK CONSTRAINT [FK_UserFixSession_FixSession];

ALTER TABLE [dbo].[Wheel] WITH CHECK CHECK CONSTRAINT [FK_Wheel_Firm];

ALTER TABLE [dbo].[WheelDestination] WITH CHECK CHECK CONSTRAINT [FK_WheelDestination_FirmDestination];

ALTER TABLE [dbo].[WheelDestination] WITH CHECK CHECK CONSTRAINT [FK_WheelDestination_Wheel];


GO
PRINT N'Update complete.';


GO
